version: '3.8'

services:
  web:
    build: .
    ports:
      - "8055:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=usuario_tareas
      - DB_PASSWORD=password_seguro
      - DB_NAME=app_tareas
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=usuario_tareas
      - POSTGRES_PASSWORD=password_seguro
      - POSTGRES_DB=app_tareas
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
